version: "3.8"

x-configs:
    - &policy
      restart: always
    - &logging
      logging:
          driver: "json-file"
          options:
              max-file: 5
              max-size: 10m

services:

    next:
        build:
            context: ./
            target: prod
        ports:
            - "80:3000"
        <<: [ *logging, *policy ]
